services:
  backend:
    build:
      context: ./backend
    ports:
      - "5003:5000"
    networks:
      - mynetwork
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb

  frontend:
    build:
      context: ./frontend
    ports:
      - "5001:80"
    networks:
      - mynetwork

  mongo:
    image: mongo:latest
    ports:
      - "27000:27017"
    networks:
      - mynetwork
    volumes:
      - mongo-data:/data/db

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo-data: