version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  frontend-admin:
    build:
      context: ./frontend-admin
    ports:
      - "5001:80"
    networks:
      - mynetwork

  frontend-doctor:
    build:
      context: ./frontend-doctor
    ports:
      - "5002:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
